//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Salix.AspNetCore.Utilities.Pages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Html {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Html() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Salix.AspNetCore.Utilities.Pages.Html", typeof(Html).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;Application Errors&lt;/title&gt;
        ///    &lt;style&gt;
        ///      body{
        ///        font-family: &quot;Segoe UI&quot;, Roboto, Arial, sans-serif;
        ///        font-size: 1rem;
        ///        font-weight: 400;
        ///        line-height: 1.5;
        ///        background-color: rgb(255, 255, 240);
        ///        color: black;
        ///        padding: 1em;
        ///        padding-top: 0;
        ///      }
        ///      h1, h2, h3, h4 {
        ///        font-family: &quot;Segoe UI Light&quot;, Robo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string config_errors {
            get {
                return ResourceManager.GetString("config_errors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;API Health&lt;/title&gt;
        ///    &lt;style&gt;
        ///      body{
        ///        font-family: &quot;Segoe UI&quot;, Roboto, Arial, sans-serif;
        ///        font-size: 1rem;
        ///        font-weight: 400;
        ///        line-height: 1.5;
        ///        background-color: rgb(30, 30, 47);
        ///        color: #b1b1b5;
        ///        padding: 1em;
        ///        padding-top: 0;
        ///      }
        ///      h1, h2, h3, h4 {
        ///        font-family: &quot;Segoe UI Light&quot;, Roboto, Arial, sans-serif;
        ///        font-weight: 200 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string health {
            get {
                return ResourceManager.GetString("health", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;{ApiName}&lt;/title&gt;
        ///    &lt;style&gt;
        ///      body{
        ///        font-family: &quot;Segoe UI&quot;, Roboto, Arial, sans-serif;
        ///        font-size: 1rem;
        ///        font-weight: 400;
        ///        line-height: 1.5;
        ///        background-color: rgb(30, 30, 47);
        ///        color: #b1b1b5;
        ///        padding: 1em;
        ///        padding-top: 0;
        ///      }
        ///      h1, h2, h3, h4 {
        ///        font-family: &quot;Segoe UI Light&quot;, Roboto, Arial, sans-serif;
        ///        font-weight: 200; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string index {
            get {
                return ResourceManager.GetString("index", resourceCulture);
            }
        }
    }
}
